name: qa-vpodc-helm

# What branch of helm -- http://github.com/uc-cdis/gen3-helm
helmBranch: feat/cleanup_webapi_client_job_after_done

# What branch of gitops -- http://github.com/uc-cdis/gen3-gitops-dev
gitopsBranch: master
