apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-environments
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops-dev.git'
      targetRevision: master
      path: devplanetv2/dev-environments
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true