global:
  # Disabling local Elasticasearch and Postgres. 
  dev: false
  aws:
    enabled: true
    account: "707767160287"
    scheme: "internal"
    secretStoreServiceAccount:
      enabled: true
      name: secret-store-sa
    wafv2:
      enabled: true
      wafAclArn: "arn:aws:wafv2:us-east-1:707767160287:regional/webacl/devplanetv2-waf/30660590-f707-4ecf-aeae-ddfbe381f388"
  netPolicy:
    # TODO: Figure out netpols with local dbs
    enabled: false
    dbSubnet: ""
  environment: jian
  externalSecrets:
    deploy: true
    dbCreate: true
    pushSecret: true
  hostname: jian.dev.planx-pla.net
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/datadictionary/develop/schema.json
  # We disable portal by default to save $$$
  # frontendRoot: gen3ff
  postgres:
    dbCreate: true
    externalSecret: "devplanetv2-aurora-master-dbcreds"
    master:
      host: "devplanetv2-aurora-cluster-new.cluster-cwvizkxhzjt8.us-east-1.rds.amazonaws.com"
  # Wildcard cert for  *.dev.planx-pla.net
  revproxyArn: arn:aws:acm:us-east-1:707767160287:certificate/798e629d-05ee-4bc5-b51f-a86861f29b68
  crossplane:
    # -- (bool) Set to true if deploying to AWS and want to use crossplane for AWS resources.
    enabled: true
    # The name of the crossplane provider config.
    providerConfigName: provider-aws
    # OIDC provider URL. This is used for authentication of roles/service accounts.
    oidcProviderUrl: "oidc.eks.us-east-1.amazonaws.com/id/F057519C0E32B7DE2580904C4007BB21"
    # The account ID of the AWS account.
    accountId: "707767160287"
    s3:
      # The kms key id for the s3 bucket.
      kmsKeyId: "387b8ebf-c8b8-4887-9b2c-639aee77654c"
  topologySpread:
    # -- (bool) Whether to enable topology spread constraints for all subcharts that support it.
    enabled: true
    # -- (string) The topology key to use for spreading. Defaults to "topology.kubernetes.io/zone".
    topologyKey: "topology.kubernetes.io/zone"
    # -- (int) The maxSkew to use for topology spread constraints. Defaults to 1.
    maxSkew: 1

aws-sigv4-proxy:
  enabled: true
  esEndpoint: vpc-devplanetv2-gen3-metadata-2-xkwr2f3gbxua5mqqi7rhnat4la.us-east-1.es.amazonaws.com
ambassador:
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
ambassador-gen3:
  enabled: false
  image:
    tag: 0.60.3
arborist:
  enabled: true
  image:
    tag: master
audit:
  externalSecrets:
    createK8sAuditSecret: true
  image:
    tag: master
  enabled: true
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  # image:
  #   repository: audit
  #   tag: local
  #   pullPolicy: Never

datareplicate:
  enabled: true
  suspendCronjob: true
  externalSecrets:
    deploy: true
    googleCredsSecret: binamb-gcloud-creds-secret
    dcfDataserviceSettingsSecret: jian-dcf-dataservice-settings-secrets
    awsCredsSecret: jian-dcf-aws-creds-secret
  image:
  # -- (string) Docker repository.
    repository: quay.io/cdis/dcf-dataservice
    # -- (string) Overrides the image tag whose default is the chart appVersion.
    tag: "master"
  googleBucketReplicateJob:
    # -- (bool) Whether to enable the Google bucket replicate job
    enabled: true
    PROJECT: dcf-prod-buckets
    MAX_WORKERS: 80
    RELEASE: DR43
    MANIFEST_FILE: gs://test-data-replication-manifest/GDC_only_3plusgig_open_active_manifest.tsv
    IGNORED_FILE: gs://test-data-replication-manifest/ignored_files_manifest.csv
    LOG_BUCKET: test-data-replication-manifest
  removeObjectsFromCloudsJob:
    suspendCronjob: true
    schedule: "*/30 * * * *"
    enabled: true
    DRY_RUN: "False" #Value Must be capitalized string value
    RELEASE: DR43
    MANIFEST_FILE: s3://test-data-replication-manifest/helm_test_redaction_manifest.tsv
    IGNORED_FILE: s3://test-data-replication-manifest/ignored_files_manifest.csv
    LOG_BUCKET: test-data-replication-manifest
  replicateValidationJob:
    suspendCronjob: true
    schedule: "*/30 * * * *"
    enabled: true
    RELEASE: DR43
    MANIFEST_FILE: s3://test-data-replication-manifest/helm_test_manifest.tsv
    IGNORED_FILE: s3://test-data-replication-manifest/ignored_files_manifest.csv
    LOG_BUCKET: test-data-replication-manifest
    OUT_FILES: replication_validation_output_manifest.tsv
    FORCE_CREATE_MANIFEST: true
etl:
  enabled: true
  etlMapping:
    mappings:
      - name: mmrf_case
        doc_type: case
        type: aggregator
        root: case
        props:
          - name: project_id
          - name: submitter_id
          - name: batch_id
          - name: disease_type
          - name: index_date
          - name: primary_site
      - name: mmrf_data_file
        doc_type: data_file
        type: collector
        root: None
        category: data_file
        props:
          - name: source_node
          - name: project_id
          - name: submitter_id
          - name: object_id
          - name: md5sum
          - name: file_name
          - name: file_size
          - name: data_format
          - name: data_type
          - name: data_category
          - name: experimental_strategy
          - name: platform

  # image:
  # tube:
  #repository: tube
  # tag: master
  esEndpoint: "gen3-elasticsearch-master"

frontend-framework:
  # image:
  #   tag: main
  #   repository:
  enabled: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "15m"

guppy:
  enabled: false
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  image:
    repository: quay.io/cdis/guppy
    tag: master
  esEndpoint: http://elasticsearch:9200
  
hatchery:
  externalSecrets:
    createK8sStataSecret: true
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  image:
    tag: master
  hatchery:
    sidecarContainer:
      image: quay.io/cdis/gen3fuse-sidecar:master
      command:
        - /bin/bash
        - /sidecarDockerrun.sh
    containers:
      - target-port: 8888
        cpu-limit: "2"
        memory-limit: 3Gi
        name: "(Tutorials) Example Analysis Jupyter Lab Notebooks"
        image: quay.io/cdis/jupyter-superslim:1.0.5
        env:
          FRAME_ANCESTORS: https://{{ .Values.global.hostname }}
        args:
          - "--NotebookApp.base_url=/lw-workspace/proxy/"
          - "--NotebookApp.default_url=/lab"
          - "--NotebookApp.password=''"
          - "--NotebookApp.token=''"
          - "--NotebookApp.shutdown_no_activity_timeout=5400"
          - "--NotebookApp.quit_button=False"
        command:
          - start-notebook.sh
        path-rewrite: "/lw-workspace/proxy/"
        use-tls: "false"
        ready-probe: "/lw-workspace/proxy/"
        lifecycle-post-start:
          - "/bin/sh"
          - "-c"
          - export IAM=`whoami`; rm -rf /home/$IAM/pd/dockerHome; rm -rf /home/$IAM/pd/lost+found;
            ln -s /data /home/$IAM/pd/; true
        user-uid: 1000
        fs-gid: 100
        user-volume-location: "/home/jovyan/pd"
        gen3-volume-location: "/home/jovyan/.gen3"

indexd:
  enabled: true
  image:
    tag: master
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  defaultPrefix: dev/
  externalSecrets:
    createK8sServiceCredsSecret: true

manifestservice:
  enabled: true
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  externalSecrets:
    createK8sManifestServiceSecret: true

metadata:
  externalSecrets:
    createK8sMetadataSecret: true
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  # image:
  # repository:
  # tag:
  enabled: false
  useAggMds: "True"
  # -- (string) Namespace to use if AggMds is enabled.
  aggMdsNamespace: default
  aggMdsConfig: |
    {
      "gen3_commons": {
        "HEAL": {
          "mds_url": "https://data.midrc.org/", 
          "commons_url" : "data.midrc.org",
          "adapter": "gen3",
          "config" : {
            "guid_type": "discovery_metadata",
            "study_field": "gen3_discovery"
          },
        "keep_original_fields": false,
        "field_mappings" : {
        "authz": "path:authz",
        "tags": "path:tags",
        "_unique_id": "path:_unique_id",
        "study_id": "path:_unique_id",
        "study_description": "path:data_description",
        "full_name": "path:full_name",
        "short_name": "path:short_name",
        "commons": "Medical Imaging and Data Resource Center (MIDRC)",
        "study_url": "path:data_url",
        "_subjects_count" : {"path":"cases_count", "default" : 0 },
        "__manifest": "path:__manifest",
        "commons_url" : "data.midrc.org"
      }
      }
      },
      "adapter_commons": {}
    }

peregrine:
  enabled: true
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  image:
    repository: quay.io/cdis/peregrine
    tag: master

portal:
  enabled: true
  # 
  # resources:
  #   requests:
  #     cpu: "15m"
  #     memory: 100Mi
  image:
    repository: quay.io/cdis/data-portal
    tag: master

requestor:
  enabled: false

revproxy:
  enabled: true
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  ingress:
    aws:
      # Do not change- this will break DNS for your env.
      group: devplanetv2-internal
sheepdog:
  enabled: true
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: "2026.06"

sower:
  enabled: false

ssjdispatcher:
  enabled: false

wts:
  enabled: true
  image:
    tag: master
  resources:
    requests:
      memory: "105Mi"
      cpu: "15m"
  externalSecrets:
    createWtsOidcClientSecret: true
    createK8sWtsSecret: true


# Database configuration

elasticsearch:
  persistence:
    enabled: true

# -- (map) To configure postgresql subchart
postgresql:
  primary:
    persistence:
      # -- (bool) Option to persist the dbs data.
      enabled: true

fence:
  enabled: true
  image:
    tag: chore_test-ras
  externalSecrets:
    createK8sFenceConfigSecret: false
    createK8sJwtKeysSecret: true
    createK8sGoogleAppSecrets: true
    fenceGoogleAppCredsSecret: ci-fence-google-app-creds-secret
    fenceGoogleStorageCredsSecret: ci-fence-google-storage-creds-secret
    fenceConfig: "jian-fence-config"
    fenceJwtKeys: jian-jwt-fence
  usersync:
    usersync: true
    userYamlS3Path: s3://cdis-gen3-users/dev/user.yaml
  FENCE_CONFIG_PUBLIC:
    BASE_URL: https://jian.dev.planx-pla.net/user
    # Prefix to namespace Google Groups on a single Cloud Identity
    # This will be dynamically replaced by env_setup.sh script.
    LOGIN_OPTIONS:
      - name: NIH Login
        idp: ras
      - name: Google Login
        idp: google