apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: 2.1.3
    helm:
      values: |        
        configs:
          eventbus: |
            apiVersion: argoproj.io/v1alpha1
            kind: EventBus
            metadata:
              name: default
              namespace: argo-events
            spec:
              nats:
                native:
                  replicas: 3
                  auth: token
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences in certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  
  # Health check configuration
  revisionHistoryLimit: 10