apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-dev-{{ .Values.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: {{ .Values.helmBranch }}
      helm:
        releaseName: {{ .Values.Name }}
        valueFiles:
          - $values/devplanetv2/dev-environments/{{ .Values.name }}/values/values.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops-dev.git'
      targetRevision: {{ .Values.gitopsBranch }}
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.name }}
  ignoreDifferences:
    - 
      kind: "Secret"
      jsonPointers:
      - /data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
