apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-dev-{{ .Values.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: {{ .Values.helmBranch }}
      helm:
        releaseName: {{ .Values.Name }}
        valueFiles:
          - $values/devplanetv2/dev-environments/values.yaml
          - $values/devplanetv2/dev-environments/qureshi/values/values.yaml
        values: |
            global:
              hostname: {{ .Values.name }}.dev.planx-pla.net
            fence:
              FENCE_CONFIG_PUBLIC:
                BASE_URL: https://{{ .Values.name }}.dev.planx-pla.net/user
            sheepdog:
              # Need this to avoid the audience issue
              fenceUrl: https://{{ .Values.name }}.dev.planx-pla.net
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops-dev.git'
      targetRevision: {{ .Values.gitopsBranch }}
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.name }}
  # So argocd doesn't change auto-generated secrets
  ignoreDifferences:
    - 
      kind: "Secret"
      jsonPointers:
      - /data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    # automated:
    #   selfHeal: false
    #   prune: true
